// Generates src/index.ts from the SVG files in src/assets/{icons,flags}.
// Naming: icons/double-arrow-left.svg -> DoubleArrowLeftIcon, flags/BQ-BO.svg -> FlagBQBO.
// Runs via `node --experimental-strip-types` (repo convention, see root docs:* scripts) — erasable TS syntax only.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

interface IconEntry {
  base: string;
  dir: 'icons' | 'flags';
  name: string;
}

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const outFile = join(pkgRoot, 'src/index.ts');

const svgNames = (dir: string): string[] =>
  readdirSync(join(pkgRoot, dir))
    .filter((f) => f.endsWith('.svg'))
    .map((f) => f.slice(0, -'.svg'.length))
    .sort();

const pascalCase = (name: string): string =>
  name
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');

const icons: IconEntry[] = svgNames('src/assets/icons').map((base) => ({
  base,
  dir: 'icons',
  name: `${pascalCase(base)}Icon`,
}));

const flags: IconEntry[] = svgNames('src/assets/flags').map((base) => ({
  base,
  dir: 'flags',
  name: `Flag${base.replace(/-/g, '')}`,
}));

// Flags that have no own SVG and re-export another flag's component.
const FLAG_ALIASES: Record<string, string> = {
  FlagBQ: 'FlagNL', // Caribbean Netherlands uses the Dutch flag
};

const flagExports = flags
  .map(({ name }) => name)
  .concat(Object.entries(FLAG_ALIASES).map(([alias, target]) => `${target} as ${alias}`))
  .sort((a, b) => ((a.split(' as ').pop() ?? a) < (b.split(' as ').pop() ?? b) ? -1 : 1));

const importLine = ({ base, dir, name }: IconEntry): string =>
  `import ${name} from './assets/${dir}/${base}.svg?react';`;

const content = `// AUTO-GENERATED by scripts/generate-icons.mts — do not edit by hand.
// Add SVG files to src/assets/{icons,flags} and run \`pnpm generate\` (also runs on every build).

// Icons

export * from 'lucide-react';
${icons.map(importLine).join('\n')}

// Flags

${flags.map(importLine).join('\n')}

export {
${icons.map(({ name }) => `  ${name},`).join('\n')}

${flagExports.map((entry) => `  ${entry},`).join('\n')}
}
`;

let current: string | null;
try {
  current = readFileSync(outFile, 'utf8');
} catch {
  current = null;
}

if (current === content) {
  console.log(`[generate-icons] src/index.ts is up to date (${icons.length} icons, ${flags.length} flags)`);
} else {
  writeFileSync(outFile, content);
  console.log(`[generate-icons] wrote src/index.ts (${icons.length} icons, ${flags.length} flags)`);
}
