import {
  SupportIcon,
  GlobeIcon,
  ChevronIcon,
  CloseIcon,
  ArrowBottomRightIcon,
  MenuLeftIcon,
  ChipIcon,
  CloudIcon,
  DatabaseIcon,
  ServerIcon,
  ServerRakeIcon,
  SignalIcon,
  DataIcon,
  DriveIcon,
  RamIcon,
  PrevArrowIcon,
  NextArrowIcon,
  MailIcon,
  PinIcon,
  SunIcon,
  MoonIcon,
  InfoIcon,
  BottomArrowIcon,
  PlusIcon,
  MinusIcon,
  CheckIcon,
  CheckOIcon,
  DangerIcon,
  CopyIcon,
  AnchorIcon,
  EyeIcon,
  EyeCloseIcon,
} from '@adara-cs/icons'

const icons = {
  support: SupportIcon,
  globe: GlobeIcon,
  chevron: ChevronIcon,
  close: CloseIcon,
  arrowBottomRight: ArrowBottomRightIcon,
  menuLeft: MenuLeftIcon,
  chip: ChipIcon,
  cloud: CloudIcon,
  database: DatabaseIcon,
  server: ServerIcon,
  serverRake: ServerRakeIcon,
  signal: SignalIcon,
  data: DataIcon,
  drive: DriveIcon,
  ram: RamIcon,
  prevArrow: PrevArrowIcon,
  nextArrow: NextArrowIcon,
  mail: MailIcon,
  pin: PinIcon,
  sun: SunIcon,
  moon: MoonIcon,
  info: InfoIcon,
  bottomArrow: BottomArrowIcon,
  plus: PlusIcon,
  minus: MinusIcon,
  check: CheckIcon,
  checkCircle: CheckOIcon,
  danger: DangerIcon,
  copy: CopyIcon,
  anchor: AnchorIcon,
  eye: EyeIcon,
  eyeClose: EyeCloseIcon,
} as const

export type IconName = keyof typeof icons

export const getIcon = (name: IconName) => {
  return icons[name]
}