name: Release

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

env:
  CI: true
jobs:
  pre-checks:
    name: Run Tests and Linter
    uses: ./.github/workflows/tests-and-lint.yml

  release:
    name: Release
    needs: pre-checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB }}

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Setup Git User
        shell: bash
        run: |
          git config --global user.email "196216297+adara-cloud-ci@users.noreply.github.com"
          git config --global user.name "Adara Cloud CI"

      - name: Publish versions
        uses: changesets/action@v1.9.0
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
          version: pnpm ci:version
          publish: pnpm ci:publish
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          NODE_ENV: "production"

      - name: Build storybook
        run: npm run build-storybook

      - name: Upload storybook
        uses: actions/upload-pages-artifact@v5
        with:
          path: storybook-static/

      - name: Deploy storybook to GitHub Pages
        uses: actions/deploy-pages@v5
        with:
          token: ${{ github.token }}
