name: Tests and Lint

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  lint-and-test:
    name: Tests and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Linter
        run: pnpm run lint

      - name: Resolve package versions
        id: resolve-package-versions
        shell: bash
        run: >
          echo "$(
          node -e "
           const fs = require('fs');
           const lock = fs.readFileSync('pnpm-lock.yaml', 'utf8');
           const match = lock.match(/^\s*playwright@(\d+\.\d+\.\d+):/m);
           if (!match) throw new Error('Playwright not found in pnpm-lock.yaml');
           const version = match[1];
           console.log(`PLAYWRIGHT_VERSION=${version}`);
          "
          )" >> $GITHUB_OUTPUT

      - name: Print versions
        shell: bash
        run: echo "${{ toJson(steps.resolve-package-versions.outputs) }}"

      - name: Check resolved package versions
        shell: bash
        if: |
          contains(fromJSON('[null, "", "undefined"]'), steps.resolve-package-versions.outputs.PLAYWRIGHT_VERSION)
        run: echo "Failed to resolve package versions. See log above." && exit 1

      - name: Cache Playwright
        uses: actions/cache@v5
        id: playwright-cache
        with:
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
          key: ${{ runner.os }}-playwright-${{ steps.resolve-package-versions.outputs.PLAYWRIGHT_VERSION }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Dependencies
        shell: bash
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps --only-shell

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Run Tests
        run: pnpm test
